baseURL = 'https://www.olycanlan.org/'
locale = 'en-us'
title = 'Olympia Canadian Highlander League'
theme = 'ananke'

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2
    [[menu.main]]
        identifier = "scoreboard"
        name = "Scoreboard"
        url = "/scoreboard/"
        weight = 3