package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/signal"
	"regexp"
	"strings"
	"syscall"
	"time"

	"github.com/bwmarrin/discordgo"
	"github.com/joho/godotenv"
)

// Match Recording
// input: channel
// output: table of current scores
// 1. Scan channel for posts since last scan
// 2. For each post
//   2.1 test post is a "report post"
// 2. For each report post
//   2.1 Extract players
//   2.2 Extract scores
//   2.3 Extract match type e.g. bounty, non-bounty first, non-bounty repeated
//   2.4 Return "Report" with above info
// 3. For each player
//   3.1 Calculate new points for player based on Reports
// 4. Update Discord scoreboard post with new and total points
// 5. Update website scoreboard with new and total points

const prefix string = "!skbot"

type Match_Result struct {
	winner string
	loser  string
	result string
	bounty bool
}

type League_Player struct {
	discord_userid string
	discord_name   string
	player_type    string
	decklist       string
}

// slash command global variable
var commands = []*discordgo.ApplicationCommand{
	{
		Name:        "ping",
		Description: "Replies with Pong!",
	},
}

func registerCommands(s *discordgo.Session) {

	err := godotenv.Load()
	if err != nil {
		log.Fatalln("Error loading enironment variables:", err)
	}

	for _, cmd := range commands {
		_, err := s.ApplicationCommandCreate(
			s.State.User.ID,
			os.Getenv("GUILD_ID"), // <- empty to create a global command (GPT)
			cmd,
		)

		if err != nil {
			log.Printf("Cannot create comand %s: %v", cmd.Name, err)
		}
	}
}

func main() {
	// start by loading things like API tokens from the .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatalln("Error loading enironment variables:", err)
	} else {
		log.Println("Tokens loaded.")
	}

	// then set up the connection to Discord as the bot
	discord, err := discordgo.New("Bot " + os.Getenv("DISCORD_TOKEN"))
	if err != nil {
		log.Fatalln("Error connecting to Discord:", err)
	} else {
		log.Println("Discord sucessfully connected.")
	}

	// test the connection to Discord by getting information about the e.g. General channel
	//gnrl_id := os.Getenv("CHNL_ID")
	//chnl, err := discord.Channel(gnrl_id)
	//if err != nil {
	//	log.Fatalln("Error getting channel id\n", err)
	//}
	//log.Println(chnl)

	//regex to parse only the numbers from a string (for userIDs)
	userIDRegex := regexp.MustCompile(`[^0-9]+`)

	//---------------------------------------------------------------------//
	//TESTING GROUNDS

	//Slash command handler
	discord.AddHandler(func(s *discordgo.Session, i *discordgo.InteractionCreate) {
		//Ensures its a slash command
		if i.Type != discordgo.InteractionApplicationCommand {
			return
		}

		switch i.ApplicationCommandData().Name {
		case "ping":

			err := s.InteractionRespond(
				i.Interaction,
				&discordgo.InteractionResponse{
					Type: discordgo.InteractionResponseChannelMessageWithSource,
					Data: &discordgo.InteractionResponseData{
						Content: "Pong!",
					},
				},
			)

			if err != nil {
				log.Println(err)
			}
		}
	})

	//---------------------------------------------------------------------//
	//List of commands and descriptions. Calls to this string array when interpreting a message, so add it to here first then use logic from the array (see others)
	prefix_commands := [][]string{
		{"Help", "Provides a list of available commands and their descriptions"},
		{"Hello", "Responds to a 'Hello' message and reacts with a 🍑 emoji"},
		{"Points", "Provides a link to the current canlander points list"},
		{"Scoreboard", "Provides a link to the current website scoreboard and league standings"},
	}

	//In chat command functions for the bot using the !skbot prefix.
	discord.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {
		// Handler relates to automated functions of the bot. It intakes a session (generated by our discord.go), and a trigger (in this case it is a message being sent anywhere)
		// now "m." refers to the message that triggered this handler

		// This checks if the author of a message is the bot itself. Ensuring the bot doesnt get caught in a loop
		if m.Author.ID == s.State.User.ID {
			return
		}

		//break the message into arguments to parse the prefix command "!skbot"
		msg_args := strings.Split(m.Content, " ")

		//does nothing if the prefix command is not the first part of the message
		if msg_args[0] != prefix {
			return
		}

		//constructs the message content after the prefix for command use
		command_content := strings.Join(msg_args[1:], " ")

		//determines if the command is valid by checking if command_content matches the first column of the commands array
		//dont like using "i" here, but idk....
		valid_command := false
		for cmd := range prefix_commands {
			if command_content == prefix_commands[cmd][0] {
				valid_command = true
			}
		}

		//If the command is not valid through the loop it just replies with a this message instead prompting them to fix it.
		if valid_command == false {
			s.ChannelMessageSendReply(m.ChannelID, fmt.Sprintf("Sorry <@%v>, I don't recognize that command. Please try again or use the \"%v Help\" command to view a list of available commands.", m.Author.ID, prefix), m.Reference())
			return
		}

		//Responds to a "help" message with an embedded message listing the available commands and their descriptions
		if command_content == prefix_commands[0][0] { //help

			//construct the embedded message from the commands list.
			embed := &discordgo.MessageEmbed{
				Title: fmt.Sprintf("Available %v Commands", prefix),
				Color: 0xD80621, // Canadian Flag Red 🍁
			}
			for _, cmd := range prefix_commands {
				embed.Fields = append(embed.Fields, &discordgo.MessageEmbedField{
					Name:   cmd[0],
					Value:  cmd[1],
					Inline: false,
				})
			}
			s.ChannelMessageSendEmbed(m.ChannelID, embed)
			return
		}

		// Responds to a "hello" message with a "Hello <username>!" message and reacts with a 🍑 emoji
		if command_content == prefix_commands[1][0] { //hello
			s.ChannelMessageSendReply(m.ChannelID, fmt.Sprintf("Hello <@%v>!", m.Author.ID), m.Reference())
			s.MessageReactionAdd(m.ChannelID, m.ID, "🍑")
			return
		}

		// Responds to the "points" command with link to the current canlander points list
		if command_content == prefix_commands[2][0] { //points
			s.ChannelMessageSendReply(m.ChannelID, "Here is the current canlander points list: <https://canadianhighlander.ca/points-list/>. Happy brewing!", m.Reference())
			return
		}

		// Responds to the "scoreboard" command with link to the current website scoreboard and league standings
		if command_content == prefix_commands[3][0] { //scoreboard
			s.ChannelMessageSendReply(m.ChannelID, "You can view the current scoreboard and league standings on the bot website: <https://bot.olycanlan.org/>", m.Reference())
			return
		}

	})

	//Handler related to adding reactions. Using as a method to sign up for the league.
	//Note to add functionality in the future where it instead DMs the user and requests a decklist.
	discord.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionAdd) {

		//Prevents the bot from taking action from messages outside the signup channel.
		if r.ChannelID != os.Getenv("SIGNUP_CHNL_ID") {
			return
		}

		//This prevents the bot from making any action if the message has an ❌ emoji reaction.
		//The intent is that I can add an ❌ when signups end, stopping all role changes for the league phase.
		msg, _ := s.ChannelMessage(r.ChannelID, r.MessageID)
		for _, reaction := range msg.Reactions {
			if reaction.Emoji.Name == "❌" {
				return
			}
		}

		if r.Emoji.Name == "⚔️" {

			//When someone signs up as a "battler"...
			// First we have to check if that player has participated in previous leagues (likely)
			// IF THEY ARE NEW. Gather info about them for players.json (League_Player struct)
			// IF THEY HAVE PARTICIPATED PREVIOUSLY. Update their discord_name. Grab their last decklist link.
			// Add them to the "battler" section of the players.json, copying their relevant info if they participated previously
			// Add the current battler role
			// DM the player with a notice they have signed up and request they DM the bot their decklist. If participated previously we can include their last known deck link.

			s.GuildMemberRoleAdd(r.GuildID, r.UserID, "1505974853658874050")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been signed up as a Battler ⚔️ for this season!", r.UserID))

			new_signup := League_Player{
				discord_userid: r.UserID,
				discord_name:   r.Member.DisplayName(),
				player_type:    "Battler",
				decklist:       "",
			}

			fmt.Println(new_signup)

			channel, err := s.UserChannelCreate(r.UserID)
			if err != nil {
				log.Printf("Error creating DM channel: %v\n", err)
				return
			}
			s.ChannelMessageSend(channel.ID, "Thanks for signing up as a Battler ⚔️ for this season of the Olympia Canadian Highlander league!")
			s.ChannelMessageSend(channel.ID, "Please message me a link to your decklist on Moxfield or anoter deck hosting site.")

			// Something here to capture responses. I think that might have to be above too, since its triggered by a message...
		}
		if r.Emoji.Name == "👊" {
			s.GuildMemberRoleAdd(r.GuildID, r.UserID, "1505977716543848570")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been signed up as a Jammer 👊 for this season!", r.UserID))
		}
	})

	//Partner handler for removing reactions to remove/change roles
	discord.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionRemove) {

		//Prevents the bot from taking action from messages outside the signup channel.
		if r.ChannelID != os.Getenv("SIGNUP_CHNL_ID") {
			return
		}

		//This prevents the bot from making any action if the message has an ❌ emoji reaction.
		//The intent is that I can add an ❌ when signups end, stopping all role changes for the league phase.
		msg, _ := s.ChannelMessage(r.ChannelID, r.MessageID)
		for _, reaction := range msg.Reactions {
			if reaction.Emoji.Name == "❌" {
				return
			}
		}

		if r.Emoji.Name == "⚔️" {
			s.GuildMemberRoleRemove(r.GuildID, r.UserID, "1505974853658874050")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been removed as a Battler ⚔️ for this season!", r.UserID))
		}
		if r.Emoji.Name == "👊" {
			s.GuildMemberRoleRemove(r.GuildID, r.UserID, "1505977716543848570")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been removed as a Jammer 👊 for this season!", r.UserID))
		}
	})

	//Handler for recording match results in the bounty-board channel.
	discord.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {

		//Standard check to prevent loops
		if m.Author.ID == s.State.User.ID {
			return
		}

		//Check if message is within the bounty board channel. ID stored in .env
		if m.ChannelID != os.Getenv("BOUNTY_CHNL_ID") {
			return
		}

		//Parses message
		msg_args := strings.Split(m.Content, " ")
		if msg_args[0] == "!result" {

			//Only error check currently, though could be built out to intercept other errors.
			//Possible other errors: not tagging/userID, match result > 3 games total, Bounty/Non-Bounty not specified or mispelled, etc.
			if len(msg_args) != 5 {
				s.ChannelMessageSendReply(m.ChannelID, "Invalid command format. Please use: !result <player1> <score> <player2> <match_type>. Deleting original message", m.Reference())
				s.ChannelMessageDelete(m.ChannelID, m.ID)
				return
			}

			//Construct the match_result struct.
			match_result := Match_Result{
				winner: "",
				loser:  "",
				result: "",
				bounty: false,
			}

			//Logic to parse the winner and loser based on the game results of the match.
			result_split := strings.Split(msg_args[2], "-")
			if result_split[0] > result_split[1] {
				//Using regex to extract only the numbers from the userID tags. Typical format is <@12345>, so this removes the <@> for better storage.
				match_result.winner = userIDRegex.ReplaceAllString(msg_args[1], "")
				match_result.loser = userIDRegex.ReplaceAllString(msg_args[3], "")
				match_result.result = fmt.Sprintf("%v-%v", result_split[0], result_split[1])
			} else {
				match_result.winner = userIDRegex.ReplaceAllString(msg_args[3], "")
				match_result.loser = userIDRegex.ReplaceAllString(msg_args[1], "")
				match_result.result = fmt.Sprintf("%v-%v", result_split[1], result_split[0])
			}

			//Logic to determine if the match was bounty. Default is false.
			if msg_args[4] == "Bounty" {
				match_result.bounty = true
			}

			//Read matches.json
			matches_json, err := os.ReadFile("site/data/matches.json")
			if err != nil {
				log.Printf("Error reading matches.json: %v\n", err)
				return
			}

			var matches_data map[string]interface{}

			err = json.Unmarshal(matches_json, &matches_data)
			if err != nil {
				log.Printf("Error unmarshalling matches.json: %v\n", err)
				return
			}

			//Read metadata.json
			metadata_json, err := os.ReadFile("site/data/metadata.json")
			if err != nil {
				log.Printf("Error reading metadata.json: %v\n", err)
				return
			}

			var metadata map[string]interface{}

			err = json.Unmarshal(metadata_json, &metadata)
			if err != nil {
				log.Printf("Error unmarshalling metadata.json: %v\n", err)
				return
			}

			//Get season number & make prefix
			current_season := int(metadata["current_season"].(map[string]interface{})["season"].(float64))
			season_prefix := fmt.Sprintf("S%02d", current_season)

			//Read current season matches & metadata
			current_season_matches := matches_data["current_season"].(map[string]interface{})["matches"].(map[string]interface{})

			current_season_metadata := matches_data["current_season"].(map[string]interface{})["metadata"].(map[string]interface{})

			//construct the next match id of form S06-001
			next_match_id := int(current_season_metadata["next_match_id"].(float64))
			new_match_id := fmt.Sprintf("%s-%03d",
				season_prefix,
				next_match_id)

			//add the new match result to the json data
			current_season_matches[new_match_id] = map[string]interface{}{
				"winner": match_result.winner,
				"loser":  match_result.loser,
				"result": match_result.result,
				"bounty": match_result.bounty,
			}

			//increment next_match_id
			current_season_metadata["next_match_id"] = next_match_id + 1

			//Update the last update time
			matches_data["metadata"].(map[string]interface{})["last_updated"] =
				time.Now().UTC().Format(time.RFC3339)

			//Write back to the JSON data
			updated_matches_json, err := json.MarshalIndent(
				matches_data,
				"",
				"    ",
			)
			if err != nil {
				log.Printf("Error Marshalling Updated Matches Data: %v\n", err)
				return
			}

			err = os.WriteFile(
				"site/data/matches.json",
				updated_matches_json,
				0644,
			)

			if err != nil {
				log.Printf("Error writing matches.json: %v\n", err)
				return
			}

			//construct the embedded message from the match result.
			embed := &discordgo.MessageEmbed{
				Title: "Match Result Recorded",
				Fields: []*discordgo.MessageEmbedField{
					{
						Name:   match_result.result,
						Value:  fmt.Sprintf("<@%v> WON vs <@%v>", match_result.winner, match_result.loser),
						Inline: true,
					},
				},
				Footer: &discordgo.MessageEmbedFooter{
					Text: fmt.Sprintf("Bounty: %v", match_result.bounty),
				},
				Color: 0xD80621, // Canadian Flag Red 🍁
			}
			//Send embedded message
			s.ChannelMessageSendEmbed(m.ChannelID, embed)

			//Currently just prints the result to the terminal.
			//Maybe this is where it will feed into the website?
			fmt.Println(match_result)
		}
	})

	//---------------------------------------------------------------------//

	// This aligns the intents of the bot with the privileged intents.
	// Not 100% confident what this is needed for
	discord.Identify.Intents = discordgo.IntentsAllWithoutPrivileged

	//Below is copied from video. I think this essentially establishes when the session is opened or closed.
	err = discord.Open()
	if err != nil {
		log.Fatalln(err)
	}
	defer discord.Close()

	registerCommands(discord)

	//Terminal print indicating the bot is running
	fmt.Println("Bot is running")

	// "Listens" for CNTRL-C in the terminal to interrupt/close the bot once running.
	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt)
	<-sc
	fmt.Println("Bot is shutting down")
}
