package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/bwmarrin/discordgo"
	"github.com/joho/godotenv"
)

// Match Recording
// input: channel
// output: table of current scores
// 1. Scan channel for posts since last scan
// 2. For each post
//   2.1 test post is a "report post"
// 2. For each report post
//   2.1 Extract players
//   2.2 Extract scores
//   2.3 Extract match type e.g. bounty, non-bounty first, non-bounty repeated
//   2.4 Return "Report" with above info
// 3. For each player
//   3.1 Calculate new points for player based on Reports
// 4. Update Discord scoreboard post with new and total points
// 5. Update website scoreboard with new and total points

const prefix string = "!skbot"

func main() {
	// start by loading things like API tokens from the .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatalln("Error loading enironment variables:", err)
	} else {
		log.Println("Tokens loaded.")
	}

	// then set up the connection to Discord as the bot
	discord, err := discordgo.New("Bot " + os.Getenv("DISCORD_TOKEN"))
	if err != nil {
		log.Fatalln("Error connecting to Discord:", err)
	} else {
		log.Println("Discord sucessfully connected.")
	}

	// test the connection to Discord by getting information about the e.g. General channel
	gnrl_id := os.Getenv("CHNL_ID")
	chnl, err := discord.Channel(gnrl_id)
	if err != nil {
		log.Fatalln("Error getting channel id\n", err)
	}
	log.Println(chnl)

	//---------------------------------------------------------------------//

	//List of commands and descriptions. Calls to this string array when interpreting a message, so add it to here first then use logic from the array (see others)
	commands := [][]string{
		{"Help", "Provides a list of available commands and their descriptions"},
		{"Hello", "Responds to a 'Hello' message and reacts with a 🍑 emoji"},
		{"Points", "Provides a link to the current canlander points list"},
		{"Scoreboard", "Provides a link to the current website scoreboard and league standings"},
	}

	//First automated function. Respond to "hello" with "Hello <username>!"
	discord.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {
		// Handler relates to automated functions of the bot. It intakes a session (generated by our discord.go), and a trigger (in this case it is a message being sent anywhere)
		// now "m." refers to the message that triggered this handler

		// This checks if the author of a message is the bot itself. Ensuring the bot doesnt get caught in a loop
		if m.Author.ID == s.State.User.ID {
			return
		}

		//break the message into arguments to parse the prefix command "!skbot"
		msg_args := strings.Split(m.Content, " ")

		//does nothing if the prefix command is not the first part of the message
		if msg_args[0] != prefix {
			return
		}

		//constructs the message content after the prefix for command use
		command_content := strings.Join(msg_args[1:], " ")

		//determines if the command is valid by checking if command_content matches the first column of the commands array
		//dont like using "i" here, but idk....
		valid_command := false
		for cmd := range commands {
			if command_content == commands[cmd][0] {
				valid_command = true
			}
		}

		//If the command is not valid through the loop it just replies with a this message instead prompting them to fix it.
		if valid_command == false {
			s.ChannelMessageSendReply(m.ChannelID, fmt.Sprintf("Sorry <@%v>, I don't recognize that command. Please try again or use the \"%v Help\" command to view a list of available commands.", m.Author.ID, prefix), m.Reference())
			return
		}

		//Responds to a "help" message with an embedded message listing the available commands and their descriptions
		if command_content == commands[0][0] { //help

			//construct the embedded message from the commands list.
			embed := &discordgo.MessageEmbed{
				Title: fmt.Sprintf("Available %v Commands", prefix),
				Color: 0x00ff00, // Green color
			}
			for _, cmd := range commands {
				embed.Fields = append(embed.Fields, &discordgo.MessageEmbedField{
					Name:   cmd[0],
					Value:  cmd[1],
					Inline: false,
				})
			}
			s.ChannelMessageSendEmbed(m.ChannelID, embed)
			return
		}

		// Responds to a "hello" message with a "Hello <username>!" message and reacts with a 🍑 emoji
		if command_content == commands[1][0] { //hello
			s.ChannelMessageSendReply(m.ChannelID, fmt.Sprintf("Hello <@%v>!", m.Author.ID), m.Reference())
			s.MessageReactionAdd(m.ChannelID, m.ID, "🍑")
			return
		}

		// Responds to the "points" command with link to the current canlander points list
		if command_content == commands[2][0] { //points
			s.ChannelMessageSendReply(m.ChannelID, "Here is the current canlander points list: <https://canadianhighlander.ca/points-list/>. Happy brewing!", m.Reference())
			return
		}

		// Responds to the "scoreboard" command with link to the current website scoreboard and league standings
		if command_content == commands[3][0] { //scoreboard
			s.ChannelMessageSendReply(m.ChannelID, "You can view the current scoreboard and league standings on the bot website: <https://bot.olycanlan.org/>", m.Reference())
			return
		}

	})

	//Handler related to adding reactions. Using as a method to sign up for the league.
	//Will need a partner handler for removing reactions to remove roles during signup season.
	//Maybe also a way to indicate when signup season begins and ends?
	discord.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionAdd) {
		if r.Emoji.Name == "⚔️" {
			s.GuildMemberRoleAdd(r.GuildID, r.UserID, "1505974853658874050")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been signed up as a Battler ⚔️ for this season!", r.UserID))
		}
		if r.Emoji.Name == "👊" {
			s.GuildMemberRoleAdd(r.GuildID, r.UserID, "1505977716543848570")
			s.ChannelMessageSend(r.ChannelID, fmt.Sprintf(" <@%v> has been signed up as a Jammer 👊 for this season!", r.UserID))
		}
	})

	// This aligns the intents of the bot with the privileged intents.
	// Not 100% confident what this is needed for
	discord.Identify.Intents = discordgo.IntentsAllWithoutPrivileged

	//Below is copied from video. I think this essentially establishes when the session is opened or closed.
	err = discord.Open()
	if err != nil {
		log.Fatalln(err)
	}
	defer discord.Close()

	//Terminal print indicating the bot is running
	fmt.Println("Bot is running")

	// "Listens" for CNTRL-C in the terminal to interrupt/close the bot once running.
	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt)
	<-sc
	fmt.Println("Bot is shutting down")
}
